// Gerado a partir de uma varredura do OpenStreetMap (Overpass API) dos bairros
// de Sorocaba dentro de um raio de 7km da loja (Rua Pedro Lombardi, 890 —
// Vila Mineirão). Serve como referência rápida e confiável de bairro -> taxa,
// evitando depender de geocodificação ao vivo (Nominatim) para bairros comuns.
// Taxa = ceil(km) * R$1,10/km. Bairros aqui NÃO aparecem no painel admin
// (Taxas de entrega) — aquela tabela continua sendo a fonte de verdade para
// overrides manuais, que tem prioridade sobre esta lista.
export type BairroRef = { name: string; km: number; fee: number };

export const BAIRROS_7KM: BairroRef[] = [
  { name: "Vila Mineirão", km: 0.21, fee: 1.1 },
  { name: "Jardim Botânico", km: 0.51, fee: 1.1 },
  { name: "Jardim Guadalupe", km: 0.55, fee: 1.1 },
  { name: "Comunidade Urbana Mineirão - Jardim Guadalupe", km: 0.61, fee: 1.1 },
  { name: "Jardim Hungarês", km: 0.65, fee: 1.1 },
  { name: "CESO - Centro Empresarial de Sorocaba", km: 0.67, fee: 1.1 },
  { name: "Vila Aracelis", km: 0.69, fee: 1.1 },
  { name: "Jardim Brasilândia", km: 0.79, fee: 1.1 },
  { name: "Jardim Vicente Silvano", km: 0.88, fee: 1.1 },
  { name: "Vila Melges", km: 0.90, fee: 1.1 },
  { name: "Jardim São Conrado", km: 0.92, fee: 1.1 },
  { name: "Jardim São Mateus", km: 0.94, fee: 1.1 },
  { name: "Jardim Maria Christina", km: 0.98, fee: 1.1 },
  { name: "Jardim São Lorenzo", km: 1.00, fee: 2.2 },
  { name: "Jardim Montevideo", km: 1.02, fee: 2.2 },
  { name: "Vila Almeida", km: 1.05, fee: 2.2 },
  { name: "Jardim Siriema", km: 1.05, fee: 2.2 },
  { name: "Jardim Portugal", km: 1.08, fee: 2.2 },
  { name: "Vila Asseituno", km: 1.08, fee: 2.2 },
  { name: "Jardim Neuza Maria", km: 1.11, fee: 2.2 },
  { name: "Jardim Santa Márcia", km: 1.15, fee: 2.2 },
  { name: "Vila Fiori", km: 1.15, fee: 2.2 },
  { name: "Jardim Andréa Pilungo", km: 1.22, fee: 2.2 },
  { name: "Jardim Gavin", km: 1.29, fee: 2.2 },
  { name: "Chácaras Antão Arruda", km: 1.30, fee: 2.2 },
  { name: "Jardim Santo André", km: 1.30, fee: 2.2 },
  { name: "Vila Esperança", km: 1.34, fee: 2.2 },
  { name: "Vila Formosa", km: 1.38, fee: 2.2 },
  { name: "Vila Emílio Peres", km: 1.43, fee: 2.2 },
  { name: "Jardim Paraná", km: 1.43, fee: 2.2 },
  { name: "Jardim Abaeté", km: 1.43, fee: 2.2 },
  { name: "Vila Primavera", km: 1.46, fee: 2.2 },
  { name: "Vila Josefina", km: 1.46, fee: 2.2 },
  { name: "Jardim Germiniani", km: 1.48, fee: 2.2 },
  { name: "Jardim San Raphael", km: 1.49, fee: 2.2 },
  { name: "Jardim Ferreira", km: 1.50, fee: 2.2 },
  { name: "Parque Empresarial das Mangueiras", km: 1.50, fee: 2.2 },
  { name: "Jardim Guaíba I", km: 1.54, fee: 2.2 },
  { name: "Vila Barros", km: 1.55, fee: 2.2 },
  { name: "Jardim São Fernando", km: 1.56, fee: 2.2 },
  { name: "Jardim das Acácias", km: 1.57, fee: 2.2 },
  { name: "Vila do Netinho", km: 1.59, fee: 2.2 },
  { name: "Vila Jorge Guilherme Senger", km: 1.60, fee: 2.2 },
  { name: "Jardim Guaíba II", km: 1.61, fee: 2.2 },
  { name: "Jardim Maria Antonia Prado", km: 1.63, fee: 2.2 },
  { name: "Vila Guimarães", km: 1.63, fee: 2.2 },
  { name: "Vila Carol", km: 1.65, fee: 2.2 },
  { name: "Jardim Eugênio Silvano", km: 1.67, fee: 2.2 },
  { name: "Jardim Maria do Carmo", km: 1.74, fee: 2.2 },
  { name: "Vila Gabriel", km: 1.74, fee: 2.2 },
  { name: "Vila Diego", km: 1.75, fee: 2.2 },
  { name: "Vila Olímpia", km: 1.80, fee: 2.2 },
  { name: "Jardim Marnilda", km: 1.80, fee: 2.2 },
  { name: "Vila Leopoldina", km: 1.82, fee: 2.2 },
  { name: "Jardim Atílio Silvano", km: 1.83, fee: 2.2 },
  { name: "Vila Nova", km: 1.85, fee: 2.2 },
  { name: "Vila Juliana", km: 1.85, fee: 2.2 },
  { name: "Vila Theodolinda", km: 1.86, fee: 2.2 },
  { name: "Vila Odim Antão", km: 1.87, fee: 2.2 },
  { name: "Jardim Alvorada", km: 1.88, fee: 2.2 },
  { name: "Jardim Tortelli", km: 1.88, fee: 2.2 },
  { name: "Jardim Santa Lúcia", km: 1.90, fee: 2.2 },
  { name: "Jardim Rosa Maria", km: 1.91, fee: 2.2 },
  { name: "Parque das Laranjeiras", km: 1.92, fee: 2.2 },
  { name: "Vila Josué dos Santos", km: 1.93, fee: 2.2 },
  { name: "Jardim Sorocabano", km: 1.95, fee: 2.2 },
  { name: "Vila Gomes", km: 1.95, fee: 2.2 },
  { name: "Jardim Altos do Itavuvu", km: 1.99, fee: 2.2 },
  { name: "Jardim Ibiti Reserva II (proposto)", km: 2.00, fee: 2.2 },
  { name: "Jardim Manoel Affonso", km: 2.03, fee: 3.3 },
  { name: "Vila Adélia", km: 2.06, fee: 3.3 },
  { name: "Jardim Leandro Dromani", km: 2.06, fee: 3.3 },
  { name: "Jardim Fátima", km: 2.07, fee: 3.3 },
  { name: "Jardim Antonio Gomes", km: 2.08, fee: 3.3 },
  { name: "Vila Guilherme", km: 2.08, fee: 3.3 },
  { name: "Jardim Marco Antônio", km: 2.09, fee: 3.3 },
  { name: "Vila Pereira de Souza", km: 2.09, fee: 3.3 },
  { name: "Vila Egídio", km: 2.09, fee: 3.3 },
  { name: "Jardim do Carmo", km: 2.12, fee: 3.3 },
  { name: "Vila Progresso", km: 2.12, fee: 3.3 },
  { name: "Vila Angélica", km: 2.12, fee: 3.3 },
  { name: "Jardim Wilma", km: 2.19, fee: 3.3 },
  { name: "Vila Álvaro Soares", km: 2.21, fee: 3.3 },
  { name: "Retiro São João", km: 2.21, fee: 3.3 },
  { name: "Núcleo Habitacional Retiro São João", km: 2.22, fee: 3.3 },
  { name: "Jardim Edgar Marques", km: 2.24, fee: 3.3 },
  { name: "Jardim Santa Rita", km: 2.27, fee: 3.3 },
  { name: "Jardim Ipanema", km: 2.27, fee: 3.3 },
  { name: "Jardim Santa Marina II", km: 2.31, fee: 3.3 },
  { name: "Recreio Marajoara", km: 2.33, fee: 3.3 },
  { name: "Jardim Santa Cláudia I e II", km: 2.35, fee: 3.3 },
  { name: "Vila Cândido Ribeiro", km: 2.35, fee: 3.3 },
  { name: "Parque Ibiti Royal", km: 2.35, fee: 3.3 },
  { name: "Vila São Francisco", km: 2.37, fee: 3.3 },
  { name: "Vila Dionízia", km: 2.38, fee: 3.3 },
  { name: "Vila Perrella", km: 2.40, fee: 3.3 },
  { name: "Vila Clara Margarida", km: 2.40, fee: 3.3 },
  { name: "Vila Arnaldo Cunha", km: 2.40, fee: 3.3 },
  { name: "Vila Nova Sorocaba", km: 2.40, fee: 3.3 },
  { name: "Vila Mariana", km: 2.40, fee: 3.3 },
  { name: "Parque Ibiti do Paço", km: 2.41, fee: 3.3 },
  { name: "Jardim Casabranca I e II", km: 2.42, fee: 3.3 },
  { name: "Vila Carvalho", km: 2.42, fee: 3.3 },
  { name: "Vila Ana Maria", km: 2.42, fee: 3.3 },
  { name: "Vila Porcel", km: 2.43, fee: 3.3 },
  { name: "Retiro São Leopoldo", km: 2.43, fee: 3.3 },
  { name: "Vila Santana", km: 2.44, fee: 3.3 },
  { name: "Jardim Celisa Maria", km: 2.46, fee: 3.3 },
  { name: "Jardim Santa Paula II", km: 2.50, fee: 3.3 },
  { name: "Jardim Santa Catarina", km: 2.50, fee: 3.3 },
  { name: "Jardim Dois Corações", km: 2.57, fee: 3.3 },
  { name: "Vila Beatriz A. Rosa", km: 2.58, fee: 3.3 },
  { name: "Jardim Leocadia", km: 2.62, fee: 3.3 },
  { name: "Jardim Louzada", km: 2.63, fee: 3.3 },
  { name: "Jardim Sônia Maria", km: 2.63, fee: 3.3 },
  { name: "Vila Nicanor Marques", km: 2.65, fee: 3.3 },
  { name: "Jardim Imperial", km: 2.69, fee: 3.3 },
  { name: "Jardim Planalto", km: 2.70, fee: 3.3 },
  { name: "Vila Pereira", km: 2.72, fee: 3.3 },
  { name: "Jardim Colinas de São Guilherme", km: 2.73, fee: 3.3 },
  { name: "Vila Elza", km: 2.73, fee: 3.3 },
  { name: "Vila Godoy", km: 2.74, fee: 3.3 },
  { name: "Vila Palmeiras", km: 2.75, fee: 3.3 },
  { name: "Jardim Santa Rosália", km: 2.77, fee: 3.3 },
  { name: "Jardim Monte Santo", km: 2.79, fee: 3.3 },
  { name: "Jardim Vivendas do Itavuvu", km: 2.85, fee: 3.3 },
  { name: "Jardim Morumbi III e IV", km: 2.89, fee: 3.3 },
  { name: "Jardim Santa Marina I", km: 2.90, fee: 3.3 },
  { name: "Vila Campos", km: 2.97, fee: 3.3 },
  { name: "Parque das Paineiras", km: 2.97, fee: 3.3 },
  { name: "Jardim São Guilherme I", km: 2.99, fee: 3.3 },
  { name: "Jardim Santa Paula I", km: 2.99, fee: 3.3 },
  { name: "Jardim São Camilo", km: 3.01, fee: 4.4 },
  { name: "Jardim Novo Horizonte", km: 3.01, fee: 4.4 },
  { name: "Jardim Santa Rosa", km: 3.03, fee: 4.4 },
  { name: "Vila Pedro Ribeiro", km: 3.03, fee: 4.4 },
  { name: "Vila Gagliardi", km: 3.05, fee: 4.4 },
  { name: "Jardim Baronesa", km: 3.12, fee: 4.4 },
  { name: "Jardim Morumbi I e II", km: 3.16, fee: 4.4 },
  { name: "Jardim Santa Cecília", km: 3.17, fee: 4.4 },
  { name: "Jardim Maria Eugênia", km: 3.19, fee: 4.4 },
  { name: "Vila Pedreira", km: 3.19, fee: 4.4 },
  { name: "Jardim Marita", km: 3.19, fee: 4.4 },
  { name: "Jardim Saira", km: 3.19, fee: 4.4 },
  { name: "Vila Santo Antônio", km: 3.22, fee: 4.4 },
  { name: "Vila Municipal", km: 3.26, fee: 4.4 },
  { name: "Jardim Paulista II", km: 3.30, fee: 4.4 },
  { name: "Jardim Napoli", km: 3.31, fee: 4.4 },
  { name: "Iporanga", km: 3.31, fee: 4.4 },
  { name: "Jardim Santa Luíza", km: 3.35, fee: 4.4 },
  { name: "Comunicade União", km: 3.36, fee: 4.4 },
  { name: "Vila Magalhães", km: 3.36, fee: 4.4 },
  { name: "Residencial Constantino Mattucci", km: 3.36, fee: 4.4 },
  { name: "Jardim Paulista I", km: 3.37, fee: 4.4 },
  { name: "Jardim São Guilherme II", km: 3.38, fee: 4.4 },
  { name: "Jardim das Flores", km: 3.38, fee: 4.4 },
  { name: "Vila Douglas Lara", km: 3.40, fee: 4.4 },
  { name: "Vila Helena", km: 3.41, fee: 4.4 },
  { name: "Jardim Nogueira", km: 3.44, fee: 4.4 },
  { name: "Vila Eros", km: 3.44, fee: 4.4 },
  { name: "Vila Balbina", km: 3.44, fee: 4.4 },
  { name: "Jardim Marize", km: 3.45, fee: 4.4 },
  { name: "Vila Casa Nova", km: 3.46, fee: 4.4 },
  { name: "Jardim Isafer", km: 3.46, fee: 4.4 },
  { name: "Jardim Maria", km: 3.47, fee: 4.4 },
  { name: "Comunidade Urbana Jardim Santa Luíza", km: 3.47, fee: 4.4 },
  { name: "Jardim Pelegrino", km: 3.49, fee: 4.4 },
  { name: "Vila Barão", km: 3.49, fee: 4.4 },
  { name: "Jardim Santo Amaro", km: 3.51, fee: 4.4 },
  { name: "Jardim Barros França", km: 3.53, fee: 4.4 },
  { name: "Jardim Sorocaba Park", km: 3.53, fee: 4.4 },
  { name: "Comunidade Urbana Fazendinha", km: 3.59, fee: 4.4 },
  { name: "Vila Hingst", km: 3.61, fee: 4.4 },
  { name: "Vila São João", km: 3.63, fee: 4.4 },
  { name: "Jardim Portal do Itavuvu", km: 3.65, fee: 4.4 },
  { name: "Jardim Florença", km: 3.65, fee: 4.4 },
  { name: "Jardim Mathilde", km: 3.66, fee: 4.4 },
  { name: "Jardim Camila", km: 3.68, fee: 4.4 },
  { name: "Vila Aeroporto", km: 3.71, fee: 4.4 },
  { name: "Jardim Cruzeiro do Sul", km: 3.71, fee: 4.4 },
  { name: "Jardim Nova Ipanema", km: 3.72, fee: 4.4 },
  { name: "Jardim Celeste", km: 3.74, fee: 4.4 },
  { name: "Vila João Rodrigues Bueno", km: 3.74, fee: 4.4 },
  { name: "Vila Ipanema Club", km: 3.75, fee: 4.4 },
  { name: "Jardim Santa Clara", km: 3.75, fee: 4.4 },
  { name: "Jardim São Guilherme III", km: 3.75, fee: 4.4 },
  { name: "Vila Senger", km: 3.77, fee: 4.4 },
  { name: "Centro", km: 3.79, fee: 4.4 },
  { name: "Vila Santa Terezinha", km: 3.81, fee: 4.4 },
  { name: "Conjunto Habitacional Herbert de Souza", km: 3.84, fee: 4.4 },
  { name: "Cj. Habitacional Ulysses Guimarães", km: 3.84, fee: 4.4 },
  { name: "Vila Arruda", km: 3.85, fee: 4.4 },
  { name: "Vila Santa Francisca", km: 3.87, fee: 4.4 },
  { name: "Árvore Grande", km: 3.92, fee: 4.4 },
  { name: "Jardim Zulmira", km: 3.94, fee: 4.4 },
  { name: "Comunidade Urbana Iporanga - John Boyd Dunlop", km: 3.94, fee: 4.4 },
  { name: "Vila Augusto", km: 3.96, fee: 4.4 },
  { name: "Jardim Flamboyant", km: 3.97, fee: 4.4 },
  { name: "Jardim Itaipu", km: 3.98, fee: 4.4 },
  { name: "Vila Urbina", km: 4.01, fee: 5.5 },
  { name: "Bairro da Ronda", km: 4.02, fee: 5.5 },
  { name: "Vila Raszl", km: 4.02, fee: 5.5 },
  { name: "Vila Abreu", km: 4.03, fee: 5.5 },
  { name: "Além Ponte", km: 4.04, fee: 5.5 },
  { name: "Chácaras Reunidas Maria", km: 4.04, fee: 5.5 },
  { name: "Jardim Henrique", km: 4.04, fee: 5.5 },
  { name: "Boa Vista", km: 4.05, fee: 5.5 },
  { name: "Parque Vitória Régia", km: 4.06, fee: 5.5 },
  { name: "Jardim Costa Dias", km: 4.07, fee: 5.5 },
  { name: "Recreio dos Sorocabanos", km: 4.08, fee: 5.5 },
  { name: "Comunidade Urbana Jardim Itapemirim", km: 4.09, fee: 5.5 },
  { name: "Vila Bandeirante", km: 4.10, fee: 5.5 },
  { name: "Vila Chiquita", km: 4.12, fee: 5.5 },
  { name: "Vila Paraíso", km: 4.12, fee: 5.5 },
  { name: "Jardim Santa Esmeralda", km: 4.12, fee: 5.5 },
  { name: "Jardim Itapoã", km: 4.13, fee: 5.5 },
  { name: "Jardim Betânia", km: 4.15, fee: 5.5 },
  { name: "Vila Adonias", km: 4.16, fee: 5.5 },
  { name: "Vila Ondina", km: 4.16, fee: 5.5 },
  { name: "Jardim Paes de Almeida", km: 4.17, fee: 5.5 },
  { name: "Vila Nova Esperança", km: 4.17, fee: 5.5 },
  { name: "Vila Ferreira Leão", km: 4.18, fee: 5.5 },
  { name: "Vila José", km: 4.19, fee: 5.5 },
  { name: "Jardim Santa Helena", km: 4.20, fee: 5.5 },
  { name: "Vila Jandira Leão", km: 4.21, fee: 5.5 },
  { name: "Vila Augusta", km: 4.21, fee: 5.5 },
  { name: "Vila Lucy", km: 4.21, fee: 5.5 },
  { name: "Vila Santa Cruz", km: 4.22, fee: 5.5 },
  { name: "Jardim Francini", km: 4.22, fee: 5.5 },
  { name: "Jardim Bela Vista", km: 4.22, fee: 5.5 },
  { name: "Bairro do Caguassu", km: 4.23, fee: 5.5 },
  { name: "Jardim São Bento", km: 4.23, fee: 5.5 },
  { name: "Vila Marques", km: 4.24, fee: 5.5 },
  { name: "Vila Badini", km: 4.27, fee: 5.5 },
  { name: "Jardim do Paço", km: 4.29, fee: 5.5 },
  { name: "Vila Yolanda", km: 4.31, fee: 5.5 },
  { name: "Vila Marina Dias", km: 4.31, fee: 5.5 },
  { name: "Vila Independência", km: 4.32, fee: 5.5 },
  { name: "Vila Eufrásio", km: 4.33, fee: 5.5 },
  { name: "Vila Amélia", km: 4.36, fee: 5.5 },
  { name: "Residencial Horto Florestal III", km: 4.38, fee: 5.5 },
  { name: "Jardim Débora", km: 4.39, fee: 5.5 },
  { name: "Jardim Colinas do Sol", km: 4.39, fee: 5.5 },
  { name: "Jardim Bonsucesso", km: 4.40, fee: 5.5 },
  { name: "Jardim Vergueiro", km: 4.40, fee: 5.5 },
  { name: "Jardim J. S. Carvalho", km: 4.40, fee: 5.5 },
  { name: "Jardim Vitória Ville", km: 4.41, fee: 5.5 },
  { name: "Vila Rodrigues", km: 4.41, fee: 5.5 },
  { name: "Jardim Luciana Maria II", km: 4.43, fee: 5.5 },
  { name: "Jardim Piratininga", km: 4.44, fee: 5.5 },
  { name: "Jardim Mércia Maria", km: 4.44, fee: 5.5 },
  { name: "Jardim Marcelo Augusto", km: 4.45, fee: 5.5 },
  { name: "Jardim Gonçalves", km: 4.46, fee: 5.5 },
  { name: "Parque Industrial Prestes", km: 4.46, fee: 5.5 },
  { name: "Vila Alice", km: 4.47, fee: 5.5 },
  { name: "Comunidade Urbana G2-G3 (nan)", km: 4.47, fee: 5.5 },
  { name: "Parque Esmeralda", km: 4.47, fee: 5.5 },
  { name: "Vila Florinda", km: 4.49, fee: 5.5 },
  { name: "Jardim Rádio Club", km: 4.51, fee: 5.5 },
  { name: "Jardim Soares", km: 4.52, fee: 5.5 },
  { name: "Vila Matielo", km: 4.53, fee: 5.5 },
  { name: "Vila Alcoléa", km: 4.53, fee: 5.5 },
  { name: "Vila Delgado Romano", km: 4.55, fee: 5.5 },
  { name: "Wanel Ville III", km: 4.56, fee: 5.5 },
  { name: "Vila Marta", km: 4.56, fee: 5.5 },
  { name: "Residencial Horto Florestal Villagio", km: 4.57, fee: 5.5 },
  { name: "Vila Boa Vista", km: 4.57, fee: 5.5 },
  { name: "Jardim Jockey Club", km: 4.58, fee: 5.5 },
  { name: "Jardim Itapemirim", km: 4.58, fee: 5.5 },
  { name: "Vila São Pedro", km: 4.59, fee: 5.5 },
  { name: "Vila Márcia", km: 4.60, fee: 5.5 },
  { name: "Jardim Luciana Maria I", km: 4.60, fee: 5.5 },
  { name: "Vila João Gomes", km: 4.61, fee: 5.5 },
  { name: "Jardim São Lucas", km: 4.62, fee: 5.5 },
  { name: "Comunidade Urbana Ipanema Ville", km: 4.62, fee: 5.5 },
  { name: "Residencial Horto Florestal II", km: 4.62, fee: 5.5 },
  { name: "Jardim Rodrigo", km: 4.65, fee: 5.5 },
  { name: "Bairro Lopes de Oliveira (Cerrado)", km: 4.65, fee: 5.5 },
  { name: "Jardim Califórnia", km: 4.67, fee: 5.5 },
  { name: "Vila Conceição", km: 4.68, fee: 5.5 },
  { name: "Jardim Colégio", km: 4.68, fee: 5.5 },
  { name: "Jardim Colonial", km: 4.69, fee: 5.5 },
  { name: "Jardim Imperatriz", km: 4.70, fee: 5.5 },
  { name: "Jardim Marginal", km: 4.70, fee: 5.5 },
  { name: "Jardim Izabel", km: 4.73, fee: 5.5 },
  { name: "Jardim Cardoso", km: 4.74, fee: 5.5 },
  { name: "Jardim Perimetral", km: 4.75, fee: 5.5 },
  { name: "Vila Saúde", km: 4.76, fee: 5.5 },
  { name: "Jardim Paulistano", km: 4.78, fee: 5.5 },
  { name: "Parque Vitória Régia III", km: 4.81, fee: 5.5 },
  { name: "Vila Haro", km: 4.83, fee: 5.5 },
  { name: "Jardim Salesiano", km: 4.84, fee: 5.5 },
  { name: "Jardim Rosconi", km: 4.84, fee: 5.5 },
  { name: "Vila Botelho", km: 4.86, fee: 5.5 },
  { name: "Jardim Simus III", km: 4.87, fee: 5.5 },
  { name: "Jardim São Caetano", km: 4.87, fee: 5.5 },
  { name: "Jardim Monterrey", km: 4.89, fee: 5.5 },
  { name: "Vila Hortência", km: 4.89, fee: 5.5 },
  { name: "Jardim Maria Elvira", km: 4.91, fee: 5.5 },
  { name: "Jardim Alpes de Sorocaba", km: 4.92, fee: 5.5 },
  { name: "Vila Hortência IV", km: 4.92, fee: 5.5 },
  { name: "Residencial Horto Florestal I", km: 4.93, fee: 5.5 },
  { name: "Jardim Moncayo", km: 4.93, fee: 5.5 },
  { name: "Bairro dos Morros", km: 4.93, fee: 5.5 },
  { name: "Jardim Ipê", km: 4.93, fee: 5.5 },
  { name: "Jardim Ipanema Ville", km: 4.94, fee: 5.5 },
  { name: "Jardim Wanel Ville V", km: 4.94, fee: 5.5 },
  { name: "Vila Bela", km: 4.95, fee: 5.5 },
  { name: "Jardim Santa Lucinda", km: 4.96, fee: 5.5 },
  { name: "Rancho Dirce", km: 4.96, fee: 5.5 },
  { name: "Jardim Vale do Sereno", km: 4.96, fee: 5.5 },
  { name: "Vila Hortência II", km: 4.98, fee: 5.5 },
  { name: "Jardim Sol Nascente II", km: 4.99, fee: 5.5 },
  { name: "Parque Três Meninos", km: 4.99, fee: 5.5 },
  { name: "Vila Calhambeque", km: 4.99, fee: 5.5 },
  { name: "Jardim Sol Nascente", km: 5.00, fee: 6.6 },
  { name: "Jardim do Sol", km: 5.01, fee: 6.6 },
  { name: "Jardim Redenção", km: 5.02, fee: 6.6 },
  { name: "Residencial Golden Park Sigma", km: 5.02, fee: 6.6 },
  { name: "Jardim Barão de Tatuí", km: 5.02, fee: 6.6 },
  { name: "Residencial Bouganville", km: 5.03, fee: 6.6 },
  { name: "Jardim Rosa", km: 5.04, fee: 6.6 },
  { name: "Jardim Eucaliptos", km: 5.05, fee: 6.6 },
  { name: "Vila Jardini", km: 5.05, fee: 6.6 },
  { name: "Sorocaba Industrial Park (proposto)", km: 5.07, fee: 6.6 },
  { name: "Jardim Habitacional", km: 5.07, fee: 6.6 },
  { name: "Jardim Botucatu", km: 5.08, fee: 6.6 },
  { name: "Vila Olga", km: 5.10, fee: 6.6 },
  { name: "Jardim Simus II", km: 5.11, fee: 6.6 },
  { name: "Vila Assis", km: 5.11, fee: 6.6 },
  { name: "Golden Park Residence", km: 5.13, fee: 6.6 },
  { name: "Jardim Faculdade", km: 5.14, fee: 6.6 },
  { name: "Vila Pinheiro", km: 5.15, fee: 6.6 },
  { name: "Vila Souza Pinto", km: 5.15, fee: 6.6 },
  { name: "Parque Vista Bárbara", km: 5.16, fee: 6.6 },
  { name: "Jardim Eldorado", km: 5.16, fee: 6.6 },
  { name: "Jardim Wanel Ville I", km: 5.19, fee: 6.6 },
  { name: "Vila Granada", km: 5.20, fee: 6.6 },
  { name: "Jardim Martinez", km: 5.21, fee: 6.6 },
  { name: "Vila Santa Tereza", km: 5.21, fee: 6.6 },
  { name: "Vila Hortência III", km: 5.23, fee: 6.6 },
  { name: "Jardim Marli", km: 5.23, fee: 6.6 },
  { name: "Jardim Portal da Primavera", km: 5.24, fee: 6.6 },
  { name: "Jardim Wanel Ville II", km: 5.24, fee: 6.6 },
  { name: "Vila Camargo", km: 5.25, fee: 6.6 },
  { name: "Vila Cristal", km: 5.25, fee: 6.6 },
  { name: "Jardim Cauany", km: 5.26, fee: 6.6 },
  { name: "Loteamento Industrial Induspark(proposto)", km: 5.28, fee: 6.6 },
  { name: "Golden Park II", km: 5.30, fee: 6.6 },
  { name: "Jardim Mariana", km: 5.30, fee: 6.6 },
  { name: "Villa São Domingos", km: 5.31, fee: 6.6 },
  { name: "Jardim Bermejo", km: 5.31, fee: 6.6 },
  { name: "Jardim das Estrelas", km: 5.32, fee: 6.6 },
  { name: "Residencial Villagio Milano", km: 5.33, fee: 6.6 },
  { name: "Jardim Embaixador", km: 5.34, fee: 6.6 },
  { name: "Residencial Granja Olga III", km: 5.35, fee: 6.6 },
  { name: "Jardim Americano", km: 5.35, fee: 6.6 },
  { name: "Jardim Sandra", km: 5.36, fee: 6.6 },
  { name: "Jardim Emilia", km: 5.38, fee: 6.6 },
  { name: "Metropolitano Condomínio Empresarial", km: 5.38, fee: 6.6 },
  { name: "Jardim Valença", km: 5.39, fee: 6.6 },
  { name: "Jardim Santo Agostinho", km: 5.40, fee: 6.6 },
  { name: "Bairro do Lageado", km: 5.43, fee: 6.6 },
  { name: "Jardim Magnólias", km: 5.44, fee: 6.6 },
  { name: "Vila Riva", km: 5.44, fee: 6.6 },
  { name: "Jardim Panorama", km: 5.45, fee: 6.6 },
  { name: "Vila Zélia", km: 5.46, fee: 6.6 },
  { name: "Jardim Santa Madre Paulina", km: 5.46, fee: 6.6 },
  { name: "Vila Piedade", km: 5.46, fee: 6.6 },
  { name: "Jardim Pampulha", km: 5.48, fee: 6.6 },
  { name: "Residencial Vicente de Moraes", km: 5.51, fee: 6.6 },
  { name: "Vila Celso Moraes", km: 5.51, fee: 6.6 },
  { name: "Jardim Pitangui", km: 5.51, fee: 6.6 },
  { name: "Vila Elias", km: 5.52, fee: 6.6 },
  { name: "Residencial Bosque do Ipanema", km: 5.54, fee: 6.6 },
  { name: "Residencial Helena Maria", km: 5.55, fee: 6.6 },
  { name: "Jardim Palos Verdes", km: 5.55, fee: 6.6 },
  { name: "Parque Ouro Fino", km: 5.58, fee: 6.6 },
  { name: "Cidade Jardim", km: 5.60, fee: 6.6 },
  { name: "Villagio Sola", km: 5.60, fee: 6.6 },
  { name: "Residencial Júlia Martinez", km: 5.61, fee: 6.6 },
  { name: "Jardim Prestes de Barros", km: 5.62, fee: 6.6 },
  { name: "Alto da Boa Vista", km: 5.62, fee: 6.6 },
  { name: "Vila Yayá", km: 5.69, fee: 6.6 },
  { name: "Conjunto Habitacional Ana Paula Eleutério (Habiteto)", km: 5.69, fee: 6.6 },
  { name: "Jardim Judith", km: 5.69, fee: 6.6 },
  { name: "Chácara Refúgio", km: 5.71, fee: 6.6 },
  { name: "Jardim Village Verti", km: 5.71, fee: 6.6 },
  { name: "Jardim América", km: 5.73, fee: 6.6 },
  { name: "Jardim das Azaléias", km: 5.74, fee: 6.6 },
  { name: "Jardim Monte Carlo", km: 5.74, fee: 6.6 },
  { name: "Jardim Villa D'España", km: 5.74, fee: 6.6 },
  { name: "Residencial Terranova", km: 5.74, fee: 6.6 },
  { name: "Vila Gracinda", km: 5.74, fee: 6.6 },
  { name: "Villa Amarone", km: 5.76, fee: 6.6 },
  { name: "Jardim Nelisa", km: 5.79, fee: 6.6 },
  { name: "Jardim Dona Tereza", km: 5.80, fee: 6.6 },
  { name: "Jardim Le France", km: 5.81, fee: 6.6 },
  { name: "Jardim Alpino", km: 5.81, fee: 6.6 },
  { name: "Residencial Village Saint Claire", km: 5.81, fee: 6.6 },
  { name: "Jardim  Villagio Ipanema II", km: 5.82, fee: 6.6 },
  { name: "Jardim Vera Cruz I", km: 5.82, fee: 6.6 },
  { name: "Vila Popular dos Pinheiros", km: 5.83, fee: 6.6 },
  { name: "Jardim Portal da Colina", km: 5.85, fee: 6.6 },
  { name: "Villa Suíça", km: 5.87, fee: 6.6 },
  { name: "Jardim Guaporé", km: 5.89, fee: 6.6 },
  { name: "Residencial Granja Olga I", km: 5.90, fee: 6.6 },
  { name: "Jardim Itanguá II", km: 5.91, fee: 6.6 },
  { name: "Vila Inglesa", km: 5.92, fee: 6.6 },
  { name: "Jardim Abatiá", km: 5.92, fee: 6.6 },
  { name: "Jardim Europa", km: 5.92, fee: 6.6 },
  { name: "Jardim Ana Moreno", km: 5.93, fee: 6.6 },
  { name: "Parque São Bento", km: 5.94, fee: 6.6 },
  { name: "Jardim Wanel Ville IV", km: 5.94, fee: 6.6 },
  { name: "Parque Manchester", km: 5.95, fee: 6.6 },
  { name: "Jardim João Gutierres", km: 5.96, fee: 6.6 },
  { name: "Jardim Renascer", km: 5.96, fee: 6.6 },
  { name: "Residencial Vila Évora", km: 5.96, fee: 6.6 },
  { name: "Residencial Paradiso I", km: 5.97, fee: 6.6 },
  { name: "Núcleo Habitacional Itanguá II", km: 5.98, fee: 6.6 },
  { name: "Jardim Ipiranga (Lilu)", km: 5.99, fee: 6.6 },
  { name: "Jardim dos Estados", km: 6.00, fee: 6.6 },
  { name: "Jardim Itanguá I", km: 6.02, fee: 7.7 },
  { name: "Jardim Helena Cristina", km: 6.02, fee: 7.7 },
  { name: "Residencial Carmen Blanco", km: 6.03, fee: 7.7 },
  { name: "Jardim Uirapuru", km: 6.04, fee: 7.7 },
  { name: "Jardim Vem Viver (proposto)", km: 6.04, fee: 7.7 },
  { name: "Jardim Bandeirantes", km: 6.04, fee: 7.7 },
  { name: "Vila Colorau", km: 6.08, fee: 7.7 },
  { name: "Jardim Rosária Alcolea", km: 6.09, fee: 7.7 },
  { name: "Vila Azzi", km: 6.11, fee: 7.7 },
  { name: "Vila Franco", km: 6.12, fee: 7.7 },
  { name: "Vila Barcelona", km: 6.12, fee: 7.7 },
  { name: "Jardim Villagio Ipanema I", km: 6.13, fee: 7.7 },
  { name: "Vila São Vicente", km: 6.15, fee: 7.7 },
  { name: "Jardim Gramados de Sorocaba", km: 6.15, fee: 7.7 },
  { name: "Residencial Villa Olympia", km: 6.18, fee: 7.7 },
  { name: "Conjunto Habitacional São Marcos I-A", km: 6.20, fee: 7.7 },
  { name: "Jardim Cruz de Ferro", km: 6.21, fee: 7.7 },
  { name: "Residencial Villagio Itália", km: 6.23, fee: 7.7 },
  { name: "Residencial Horizontes de Sorocaba", km: 6.23, fee: 7.7 },
  { name: "Jardim Elton Ville", km: 6.23, fee: 7.7 },
  { name: "Residencial Granja Olga II", km: 6.24, fee: 7.7 },
  { name: "Jardim dos Pássaros", km: 6.27, fee: 7.7 },
  { name: "Vila Sene", km: 6.28, fee: 7.7 },
  { name: "Jardim Vera Cruz II", km: 6.28, fee: 7.7 },
  { name: "Jardim Dias Lopes", km: 6.28, fee: 7.7 },
  { name: "Comunidade Urbana Jacutinga", km: 6.28, fee: 7.7 },
  { name: "Jardim Santa Fé", km: 6.29, fee: 7.7 },
  { name: "Jardim Palmiro (proposto)", km: 6.30, fee: 7.7 },
  { name: "Residencial Dálias", km: 6.32, fee: 7.7 },
  { name: "Jardim São Marcos (fase 1)", km: 6.33, fee: 7.7 },
  { name: "Jardim Parada do Alto", km: 6.33, fee: 7.7 },
  { name: "Vila Excelsior", km: 6.34, fee: 7.7 },
  { name: "Vila Garrido", km: 6.36, fee: 7.7 },
  { name: "Village D'Avignon", km: 6.37, fee: 7.7 },
  { name: "Jardim São Marcos (fase 2)", km: 6.39, fee: 7.7 },
  { name: "Jardim Beatriz (proposto)", km: 6.39, fee: 7.7 },
  { name: "Jardim Norcross", km: 6.40, fee: 7.7 },
  { name: "Jardim Villagio Torino", km: 6.41, fee: 7.7 },
  { name: "Jardim Pagliato", km: 6.43, fee: 7.7 },
  { name: "Chácaras Castanheira", km: 6.44, fee: 7.7 },
  { name: "Jardim Casagrande", km: 6.44, fee: 7.7 },
  { name: "Jardim Novo Bandeirantes", km: 6.45, fee: 7.7 },
  { name: "Jardim Astro", km: 6.45, fee: 7.7 },
  { name: "Jardim Monte Yehi", km: 6.46, fee: 7.7 },
  { name: "Vila Espírito Santo", km: 6.48, fee: 7.7 },
  { name: "Parque São Bento II", km: 6.50, fee: 7.7 },
  { name: "Jardim Via Reggio", km: 6.52, fee: 7.7 },
  { name: "Jardim Santa Marta", km: 6.53, fee: 7.7 },
  { name: "Portal do Éden II", km: 6.53, fee: 7.7 },
  { name: "Vila Berti", km: 6.53, fee: 7.7 },
  { name: "Jardim Vittorio Emanuelle", km: 6.54, fee: 7.7 },
  { name: "Jardim Pires de Mello", km: 6.54, fee: 7.7 },
  { name: "Jardim Castanheira", km: 6.55, fee: 7.7 },
  { name: "Parque Campolim", km: 6.56, fee: 7.7 },
  { name: "Jardim Portobello", km: 6.59, fee: 7.7 },
  { name: "Central Parque", km: 6.61, fee: 7.7 },
  { name: "Vila Maria", km: 6.62, fee: 7.7 },
  { name: "Jardim Gulaberto Moreira", km: 6.63, fee: 7.7 },
  { name: "Vila Sônia", km: 6.63, fee: 7.7 },
  { name: "Jardim Villagio Wanel", km: 6.63, fee: 7.7 },
  { name: "Jardim Guarujá", km: 6.66, fee: 7.7 },
  { name: "Parque Chácara Ondina", km: 6.68, fee: 7.7 },
  { name: "Morros", km: 6.71, fee: 7.7 },
  { name: "Portal do Éden I", km: 6.71, fee: 7.7 },
  { name: "Vila João Romão", km: 6.72, fee: 7.7 },
  { name: "Vila Sabiá", km: 6.73, fee: 7.7 },
  { name: "Jardim Arco Íris", km: 6.75, fee: 7.7 },
  { name: "Jardim Guadalajara", km: 6.76, fee: 7.7 },
  { name: "Vila Paris", km: 6.79, fee: 7.7 },
  { name: "Jardim Carolina", km: 6.79, fee: 7.7 },
  { name: "Jardim Millenium", km: 6.81, fee: 7.7 },
  { name: "Vila Novo Éden", km: 6.82, fee: 7.7 },
  { name: "Conjunto Habitacional Júlio de Mesquita Filho", km: 6.83, fee: 7.7 },
  { name: "Jardim Belvedere", km: 6.85, fee: 7.7 },
  { name: "Jardim Montreal", km: 6.87, fee: 7.7 },
  { name: "Jardim Boa Esperança", km: 6.89, fee: 7.7 },
  { name: "Jardim Zezo Miguel", km: 6.92, fee: 7.7 },
  { name: "Chácara São João", km: 6.94, fee: 7.7 },
  { name: "Parque Bosque de São Bento II", km: 6.94, fee: 7.7 },
  { name: "Terras do Sol Poente", km: 6.94, fee: 7.7 },
];
