/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EntregaOrderIdRouteImport } from './routes/entrega.$orderId'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminTaxasRouteImport } from './routes/admin.taxas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminCalculadoraRouteImport } from './routes/admin.calculadora'
import { Route as AdminAbandonadosRouteImport } from './routes/admin.abandonados'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EntregaOrderIdRoute = EntregaOrderIdRouteImport.update({
  id: '/entrega/$orderId',
  path: '/entrega/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaxasRoute = AdminTaxasRouteImport.update({
  id: '/taxas',
  path: '/taxas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculadoraRoute = AdminCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonadosRoute = AdminAbandonadosRouteImport.update({
  id: '/abandonados',
  path: '/abandonados',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/abandonados': typeof AdminAbandonadosRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/taxas': typeof AdminTaxasRoute
  '/admin/login': typeof AdminLoginRoute
  '/entrega/$orderId': typeof EntregaOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/abandonados': typeof AdminAbandonadosRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/taxas': typeof AdminTaxasRoute
  '/admin/login': typeof AdminLoginRoute
  '/entrega/$orderId': typeof EntregaOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/abandonados': typeof AdminAbandonadosRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/taxas': typeof AdminTaxasRoute
  '/admin_/login': typeof AdminLoginRoute
  '/entrega/$orderId': typeof EntregaOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/meus-pedidos'
    | '/reset-password'
    | '/admin/abandonados'
    | '/admin/calculadora'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/taxas'
    | '/admin/login'
    | '/entrega/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meus-pedidos'
    | '/reset-password'
    | '/admin/abandonados'
    | '/admin/calculadora'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/taxas'
    | '/admin/login'
    | '/entrega/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/meus-pedidos'
    | '/reset-password'
    | '/admin/abandonados'
    | '/admin/calculadora'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/taxas'
    | '/admin_/login'
    | '/entrega/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MeusPedidosRoute: typeof MeusPedidosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EntregaOrderIdRoute: typeof EntregaOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entrega/$orderId': {
      id: '/entrega/$orderId'
      path: '/entrega/$orderId'
      fullPath: '/entrega/$orderId'
      preLoaderRoute: typeof EntregaOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/taxas': {
      id: '/admin/taxas'
      path: '/taxas'
      fullPath: '/admin/taxas'
      preLoaderRoute: typeof AdminTaxasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculadora': {
      id: '/admin/calculadora'
      path: '/calculadora'
      fullPath: '/admin/calculadora'
      preLoaderRoute: typeof AdminCalculadoraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandonados': {
      id: '/admin/abandonados'
      path: '/abandonados'
      fullPath: '/admin/abandonados'
      preLoaderRoute: typeof AdminAbandonadosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbandonadosRoute: typeof AdminAbandonadosRoute
  AdminCalculadoraRoute: typeof AdminCalculadoraRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminTaxasRoute: typeof AdminTaxasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonadosRoute: AdminAbandonadosRoute,
  AdminCalculadoraRoute: AdminCalculadoraRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminTaxasRoute: AdminTaxasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MeusPedidosRoute: MeusPedidosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  EntregaOrderIdRoute: EntregaOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
