INSERT INTO public.delivery_fees (neighborhood, fee) VALUES
  ('Vila Mineirão', 1.10),
  ('Jardim Botânico', 1.10),
  ('Jardim Guadalupe', 1.10),
  ('Comunidade Urbana Mineirão - Jardim Guadalupe', 1.10),
  ('Jardim Hungarês', 1.10),
  ('CESO - Centro Empresarial de Sorocaba', 1.10),
  ('Vila Aracelis', 1.10),
  ('Jardim Brasilândia', 1.10),
  ('Jardim Vicente Silvano', 1.10),
  ('Vila Melges', 1.10),
  ('Jardim São Conrado', 1.10),
  ('Jardim São Mateus', 1.10),
  ('Jardim Maria Christina', 1.10),
  ('Jardim São Lorenzo', 2.20),
  ('Jardim Montevideo', 2.20),
  ('Vila Almeida', 2.20),
  ('Jardim Siriema', 2.20),
  ('Jardim Portugal', 2.20),
  ('Vila Asseituno', 2.20),
  ('Jardim Neuza Maria', 2.20),
  ('Jardim Santa Márcia', 2.20),
  ('Vila Fiori', 2.20),
  ('Jardim Andréa Pilungo', 2.20),
  ('Jardim Gavin', 2.20),
  ('Chácaras Antão Arruda', 2.20),
  ('Jardim Santo André', 2.20),
  ('Vila Esperança', 2.20),
  ('Vila Formosa', 2.20),
  ('Vila Emílio Peres', 2.20),
  ('Jardim Paraná', 2.20),
  ('Jardim Abaeté', 2.20),
  ('Vila Primavera', 2.20),
  ('Vila Josefina', 2.20),
  ('Jardim Germiniani', 2.20),
  ('Jardim San Raphael', 2.20),
  ('Jardim Ferreira', 2.20),
  ('Parque Empresarial das Mangueiras', 2.20),
  ('Jardim Guaíba I', 2.20),
  ('Vila Barros', 2.20),
  ('Jardim São Fernando', 2.20),
  ('Jardim das Acácias', 2.20),
  ('Vila do Netinho', 2.20),
  ('Vila Jorge Guilherme Senger', 2.20),
  ('Jardim Guaíba II', 2.20),
  ('Jardim Maria Antonia Prado', 2.20),
  ('Vila Guimarães', 2.20),
  ('Vila Carol', 2.20),
  ('Jardim Eugênio Silvano', 2.20),
  ('Jardim Maria do Carmo', 2.20),
  ('Vila Gabriel', 2.20),
  ('Vila Diego', 2.20),
  ('Vila Olímpia', 2.20),
  ('Jardim Marnilda', 2.20),
  ('Vila Leopoldina', 2.20),
  ('Jardim Atílio Silvano', 2.20),
  ('Vila Nova', 2.20),
  ('Vila Juliana', 2.20),
  ('Vila Theodolinda', 2.20),
  ('Vila Odim Antão', 2.20),
  ('Jardim Alvorada', 2.20),
  ('Jardim Tortelli', 2.20),
  ('Jardim Santa Lúcia', 2.20),
  ('Jardim Rosa Maria', 2.20),
  ('Parque das Laranjeiras', 2.20),
  ('Vila Josué dos Santos', 2.20),
  ('Jardim Sorocabano', 2.20),
  ('Vila Gomes', 2.20),
  ('Jardim Altos do Itavuvu', 2.20),
  ('Jardim Ibiti Reserva II (proposto)', 2.20),
  ('Jardim Manoel Affonso', 3.30),
  ('Vila Adélia', 3.30),
  ('Jardim Leandro Dromani', 3.30),
  ('Jardim Fátima', 3.30),
  ('Jardim Antonio Gomes', 3.30),
  ('Vila Guilherme', 3.30),
  ('Jardim Marco Antônio', 3.30),
  ('Vila Pereira de Souza', 3.30),
  ('Vila Egídio', 3.30),
  ('Jardim do Carmo', 3.30),
  ('Vila Progresso', 3.30),
  ('Vila Angélica', 3.30),
  ('Jardim Wilma', 3.30),
  ('Vila Álvaro Soares', 3.30),
  ('Retiro São João', 3.30),
  ('Núcleo Habitacional Retiro São João', 3.30),
  ('Jardim Edgar Marques', 3.30),
  ('Jardim Santa Rita', 3.30),
  ('Jardim Ipanema', 3.30),
  ('Jardim Santa Marina II', 3.30),
  ('Recreio Marajoara', 3.30),
  ('Jardim Santa Cláudia I e II', 3.30),
  ('Vila Cândido Ribeiro', 3.30),
  ('Parque Ibiti Royal', 3.30),
  ('Vila São Francisco', 3.30),
  ('Vila Dionízia', 3.30),
  ('Vila Perrella', 3.30),
  ('Vila Clara Margarida', 3.30),
  ('Vila Arnaldo Cunha', 3.30),
  ('Vila Nova Sorocaba', 3.30),
  ('Vila Mariana', 3.30),
  ('Parque Ibiti do Paço', 3.30),
  ('Jardim Casabranca I e II', 3.30),
  ('Vila Carvalho', 3.30),
  ('Vila Ana Maria', 3.30),
  ('Vila Porcel', 3.30),
  ('Retiro São Leopoldo', 3.30),
  ('Vila Santana', 3.30),
  ('Jardim Celisa Maria', 3.30),
  ('Jardim Santa Paula II', 3.30),
  ('Jardim Santa Catarina', 3.30),
  ('Jardim Dois Corações', 3.30),
  ('Vila Beatriz A. Rosa', 3.30),
  ('Jardim Leocadia', 3.30),
  ('Jardim Louzada', 3.30),
  ('Jardim Sônia Maria', 3.30),
  ('Vila Nicanor Marques', 3.30),
  ('Jardim Imperial', 3.30),
  ('Jardim Planalto', 3.30),
  ('Vila Pereira', 3.30),
  ('Jardim Colinas de São Guilherme', 3.30),
  ('Vila Elza', 3.30),
  ('Vila Godoy', 3.30),
  ('Vila Palmeiras', 3.30),
  ('Jardim Santa Rosália', 3.30),
  ('Jardim Monte Santo', 3.30),
  ('Jardim Vivendas do Itavuvu', 3.30),
  ('Jardim Morumbi III e IV', 3.30),
  ('Jardim Santa Marina I', 3.30),
  ('Vila Campos', 3.30),
  ('Parque das Paineiras', 3.30),
  ('Jardim São Guilherme I', 3.30),
  ('Jardim Santa Paula I', 3.30),
  ('Jardim São Camilo', 4.40),
  ('Jardim Novo Horizonte', 4.40),
  ('Jardim Santa Rosa', 4.40),
  ('Vila Pedro Ribeiro', 4.40),
  ('Vila Gagliardi', 4.40),
  ('Jardim Baronesa', 4.40),
  ('Jardim Morumbi I e II', 4.40),
  ('Jardim Santa Cecília', 4.40),
  ('Jardim Maria Eugênia', 4.40),
  ('Vila Pedreira', 4.40),
  ('Jardim Marita', 4.40),
  ('Jardim Saira', 4.40),
  ('Vila Santo Antônio', 4.40),
  ('Vila Municipal', 4.40),
  ('Jardim Paulista II', 4.40),
  ('Jardim Napoli', 4.40),
  ('Iporanga', 4.40),
  ('Jardim Santa Luíza', 4.40),
  ('Comunicade União', 4.40),
  ('Vila Magalhães', 4.40),
  ('Residencial Constantino Mattucci', 4.40),
  ('Jardim Paulista I', 4.40),
  ('Jardim São Guilherme II', 4.40),
  ('Jardim das Flores', 4.40),
  ('Vila Douglas Lara', 4.40),
  ('Vila Helena', 4.40),
  ('Jardim Nogueira', 4.40),
  ('Vila Eros', 4.40),
  ('Vila Balbina', 4.40),
  ('Jardim Marize', 4.40),
  ('Vila Casa Nova', 4.40),
  ('Jardim Isafer', 4.40),
  ('Jardim Maria', 4.40),
  ('Comunidade Urbana Jardim Santa Luíza', 4.40),
  ('Jardim Pelegrino', 4.40),
  ('Vila Barão', 4.40),
  ('Jardim Santo Amaro', 4.40),
  ('Jardim Barros França', 4.40),
  ('Jardim Sorocaba Park', 4.40),
  ('Comunidade Urbana Fazendinha', 4.40),
  ('Vila Hingst', 4.40),
  ('Vila São João', 4.40),
  ('Jardim Portal do Itavuvu', 4.40),
  ('Jardim Florença', 4.40),
  ('Jardim Mathilde', 4.40),
  ('Jardim Camila', 4.40),
  ('Vila Aeroporto', 4.40),
  ('Jardim Cruzeiro do Sul', 4.40),
  ('Jardim Nova Ipanema', 4.40),
  ('Jardim Celeste', 4.40),
  ('Vila João Rodrigues Bueno', 4.40),
  ('Vila Ipanema Club', 4.40),
  ('Jardim Santa Clara', 4.40),
  ('Jardim São Guilherme III', 4.40),
  ('Vila Senger', 4.40),
  ('Centro', 4.40),
  ('Vila Santa Terezinha', 4.40),
  ('Conjunto Habitacional Herbert de Souza', 4.40),
  ('Cj. Habitacional Ulysses Guimarães', 4.40),
  ('Vila Arruda', 4.40),
  ('Vila Santa Francisca', 4.40),
  ('Árvore Grande', 4.40),
  ('Jardim Zulmira', 4.40),
  ('Comunidade Urbana Iporanga - John Boyd Dunlop', 4.40),
  ('Vila Augusto', 4.40),
  ('Jardim Flamboyant', 4.40),
  ('Jardim Itaipu', 4.40),
  ('Vila Urbina', 5.50),
  ('Bairro da Ronda', 5.50),
  ('Vila Raszl', 5.50),
  ('Vila Abreu', 5.50),
  ('Além Ponte', 5.50),
  ('Chácaras Reunidas Maria', 5.50),
  ('Jardim Henrique', 5.50),
  ('Boa Vista', 5.50),
  ('Parque Vitória Régia', 5.50),
  ('Jardim Costa Dias', 5.50),
  ('Recreio dos Sorocabanos', 5.50),
  ('Comunidade Urbana Jardim Itapemirim', 5.50),
  ('Vila Bandeirante', 5.50),
  ('Vila Chiquita', 5.50),
  ('Vila Paraíso', 5.50),
  ('Jardim Santa Esmeralda', 5.50),
  ('Jardim Itapoã', 5.50),
  ('Jardim Betânia', 5.50),
  ('Vila Adonias', 5.50),
  ('Vila Ondina', 5.50),
  ('Jardim Paes de Almeida', 5.50),
  ('Vila Nova Esperança', 5.50),
  ('Vila Ferreira Leão', 5.50),
  ('Vila José', 5.50),
  ('Jardim Santa Helena', 5.50),
  ('Vila Jandira Leão', 5.50),
  ('Vila Augusta', 5.50),
  ('Vila Lucy', 5.50),
  ('Vila Santa Cruz', 5.50),
  ('Jardim Francini', 5.50),
  ('Jardim Bela Vista', 5.50),
  ('Bairro do Caguassu', 5.50),
  ('Jardim São Bento', 5.50),
  ('Vila Marques', 5.50),
  ('Vila Badini', 5.50),
  ('Jardim do Paço', 5.50),
  ('Vila Yolanda', 5.50),
  ('Vila Marina Dias', 5.50),
  ('Vila Independência', 5.50),
  ('Vila Eufrásio', 5.50),
  ('Vila Amélia', 5.50),
  ('Residencial Horto Florestal III', 5.50),
  ('Jardim Débora', 5.50),
  ('Jardim Colinas do Sol', 5.50),
  ('Jardim Bonsucesso', 5.50),
  ('Jardim Vergueiro', 5.50),
  ('Jardim J. S. Carvalho', 5.50),
  ('Jardim Vitória Ville', 5.50),
  ('Vila Rodrigues', 5.50),
  ('Jardim Luciana Maria II', 5.50),
  ('Jardim Piratininga', 5.50),
  ('Jardim Mércia Maria', 5.50),
  ('Jardim Marcelo Augusto', 5.50),
  ('Jardim Gonçalves', 5.50),
  ('Parque Industrial Prestes', 5.50),
  ('Vila Alice', 5.50),
  ('Comunidade Urbana G2-G3 (nan)', 5.50),
  ('Parque Esmeralda', 5.50),
  ('Vila Florinda', 5.50),
  ('Jardim Rádio Club', 5.50),
  ('Jardim Soares', 5.50),
  ('Vila Matielo', 5.50),
  ('Vila Alcoléa', 5.50),
  ('Vila Delgado Romano', 5.50),
  ('Wanel Ville III', 5.50),
  ('Vila Marta', 5.50),
  ('Residencial Horto Florestal Villagio', 5.50),
  ('Vila Boa Vista', 5.50),
  ('Jardim Jockey Club', 5.50),
  ('Jardim Itapemirim', 5.50),
  ('Vila São Pedro', 5.50),
  ('Vila Márcia', 5.50),
  ('Jardim Luciana Maria I', 5.50),
  ('Vila João Gomes', 5.50),
  ('Jardim São Lucas', 5.50),
  ('Comunidade Urbana Ipanema Ville', 5.50),
  ('Residencial Horto Florestal II', 5.50),
  ('Jardim Rodrigo', 5.50),
  ('Bairro Lopes de Oliveira (Cerrado)', 5.50),
  ('Jardim Califórnia', 5.50),
  ('Vila Conceição', 5.50),
  ('Jardim Colégio', 5.50),
  ('Jardim Colonial', 5.50),
  ('Jardim Imperatriz', 5.50),
  ('Jardim Marginal', 5.50),
  ('Jardim Izabel', 5.50),
  ('Jardim Cardoso', 5.50),
  ('Jardim Perimetral', 5.50),
  ('Vila Saúde', 5.50),
  ('Jardim Paulistano', 5.50),
  ('Parque Vitória Régia III', 5.50),
  ('Vila Haro', 5.50),
  ('Jardim Salesiano', 5.50),
  ('Jardim Rosconi', 5.50),
  ('Vila Botelho', 5.50),
  ('Jardim Simus III', 5.50),
  ('Jardim São Caetano', 5.50),
  ('Jardim Monterrey', 5.50),
  ('Vila Hortência', 5.50),
  ('Jardim Maria Elvira', 5.50),
  ('Jardim Alpes de Sorocaba', 5.50),
  ('Vila Hortência IV', 5.50),
  ('Residencial Horto Florestal I', 5.50),
  ('Jardim Moncayo', 5.50),
  ('Bairro dos Morros', 5.50),
  ('Jardim Ipê', 5.50),
  ('Jardim Ipanema Ville', 5.50),
  ('Jardim Wanel Ville V', 5.50),
  ('Vila Bela', 5.50),
  ('Jardim Santa Lucinda', 5.50),
  ('Rancho Dirce', 5.50),
  ('Jardim Vale do Sereno', 5.50),
  ('Vila Hortência II', 5.50),
  ('Jardim Sol Nascente II', 5.50),
  ('Parque Três Meninos', 5.50),
  ('Vila Calhambeque', 5.50),
  ('Jardim Sol Nascente', 6.60),
  ('Jardim do Sol', 6.60),
  ('Jardim Redenção', 6.60),
  ('Residencial Golden Park Sigma', 6.60),
  ('Jardim Barão de Tatuí', 6.60),
  ('Residencial Bouganville', 6.60),
  ('Jardim Rosa', 6.60),
  ('Jardim Eucaliptos', 6.60),
  ('Vila Jardini', 6.60),
  ('Sorocaba Industrial Park (proposto)', 6.60),
  ('Jardim Habitacional', 6.60),
  ('Jardim Botucatu', 6.60),
  ('Vila Olga', 6.60),
  ('Jardim Simus II', 6.60),
  ('Vila Assis', 6.60),
  ('Golden Park Residence', 6.60),
  ('Jardim Faculdade', 6.60),
  ('Vila Pinheiro', 6.60),
  ('Vila Souza Pinto', 6.60),
  ('Parque Vista Bárbara', 6.60),
  ('Jardim Eldorado', 6.60),
  ('Jardim Wanel Ville I', 6.60),
  ('Vila Granada', 6.60),
  ('Jardim Martinez', 6.60),
  ('Vila Santa Tereza', 6.60),
  ('Vila Hortência III', 6.60),
  ('Jardim Marli', 6.60),
  ('Jardim Portal da Primavera', 6.60),
  ('Jardim Wanel Ville II', 6.60),
  ('Vila Camargo', 6.60),
  ('Vila Cristal', 6.60),
  ('Jardim Cauany', 6.60),
  ('Loteamento Industrial Induspark(proposto)', 6.60),
  ('Golden Park II', 6.60),
  ('Jardim Mariana', 6.60),
  ('Villa São Domingos', 6.60),
  ('Jardim Bermejo', 6.60),
  ('Jardim das Estrelas', 6.60),
  ('Residencial Villagio Milano', 6.60),
  ('Jardim Embaixador', 6.60),
  ('Residencial Granja Olga III', 6.60),
  ('Jardim Americano', 6.60),
  ('Jardim Sandra', 6.60),
  ('Jardim Emilia', 6.60),
  ('Metropolitano Condomínio Empresarial', 6.60),
  ('Jardim Valença', 6.60),
  ('Jardim Santo Agostinho', 6.60),
  ('Bairro do Lageado', 6.60),
  ('Jardim Magnólias', 6.60),
  ('Vila Riva', 6.60),
  ('Jardim Panorama', 6.60),
  ('Vila Zélia', 6.60),
  ('Jardim Santa Madre Paulina', 6.60),
  ('Vila Piedade', 6.60),
  ('Jardim Pampulha', 6.60),
  ('Residencial Vicente de Moraes', 6.60),
  ('Vila Celso Moraes', 6.60),
  ('Jardim Pitangui', 6.60),
  ('Vila Elias', 6.60),
  ('Residencial Bosque do Ipanema', 6.60),
  ('Residencial Helena Maria', 6.60),
  ('Jardim Palos Verdes', 6.60),
  ('Parque Ouro Fino', 6.60),
  ('Cidade Jardim', 6.60),
  ('Villagio Sola', 6.60),
  ('Residencial Júlia Martinez', 6.60),
  ('Jardim Prestes de Barros', 6.60),
  ('Alto da Boa Vista', 6.60),
  ('Vila Yayá', 6.60),
  ('Conjunto Habitacional Ana Paula Eleutério (Habiteto)', 6.60),
  ('Jardim Judith', 6.60),
  ('Chácara Refúgio', 6.60),
  ('Jardim Village Verti', 6.60),
  ('Jardim América', 6.60),
  ('Jardim das Azaléias', 6.60),
  ('Jardim Monte Carlo', 6.60),
  ('Jardim Villa D''España', 6.60),
  ('Residencial Terranova', 6.60),
  ('Vila Gracinda', 6.60),
  ('Villa Amarone', 6.60),
  ('Jardim Nelisa', 6.60),
  ('Jardim Dona Tereza', 6.60),
  ('Jardim Le France', 6.60),
  ('Jardim Alpino', 6.60),
  ('Residencial Village Saint Claire', 6.60),
  ('Jardim  Villagio Ipanema II', 6.60),
  ('Jardim Vera Cruz I', 6.60),
  ('Vila Popular dos Pinheiros', 6.60),
  ('Jardim Portal da Colina', 6.60),
  ('Villa Suíça', 6.60),
  ('Jardim Guaporé', 6.60),
  ('Residencial Granja Olga I', 6.60),
  ('Jardim Itanguá II', 6.60),
  ('Vila Inglesa', 6.60),
  ('Jardim Abatiá', 6.60),
  ('Jardim Europa', 6.60),
  ('Jardim Ana Moreno', 6.60),
  ('Parque São Bento', 6.60),
  ('Jardim Wanel Ville IV', 6.60),
  ('Parque Manchester', 6.60),
  ('Jardim João Gutierres', 6.60),
  ('Jardim Renascer', 6.60),
  ('Residencial Vila Évora', 6.60),
  ('Residencial Paradiso I', 6.60),
  ('Núcleo Habitacional Itanguá II', 6.60),
  ('Jardim Ipiranga (Lilu)', 6.60),
  ('Jardim dos Estados', 6.60),
  ('Jardim Itanguá I', 7.70),
  ('Jardim Helena Cristina', 7.70),
  ('Residencial Carmen Blanco', 7.70),
  ('Jardim Uirapuru', 7.70),
  ('Jardim Vem Viver (proposto)', 7.70),
  ('Jardim Bandeirantes', 7.70),
  ('Vila Colorau', 7.70),
  ('Jardim Rosária Alcolea', 7.70),
  ('Vila Azzi', 7.70),
  ('Vila Franco', 7.70),
  ('Vila Barcelona', 7.70),
  ('Jardim Villagio Ipanema I', 7.70),
  ('Vila São Vicente', 7.70),
  ('Jardim Gramados de Sorocaba', 7.70),
  ('Residencial Villa Olympia', 7.70),
  ('Conjunto Habitacional São Marcos I-A', 7.70),
  ('Jardim Cruz de Ferro', 7.70),
  ('Residencial Villagio Itália', 7.70),
  ('Residencial Horizontes de Sorocaba', 7.70),
  ('Jardim Elton Ville', 7.70),
  ('Residencial Granja Olga II', 7.70),
  ('Jardim dos Pássaros', 7.70),
  ('Vila Sene', 7.70),
  ('Jardim Vera Cruz II', 7.70),
  ('Jardim Dias Lopes', 7.70),
  ('Comunidade Urbana Jacutinga', 7.70),
  ('Jardim Santa Fé', 7.70),
  ('Jardim Palmiro (proposto)', 7.70),
  ('Residencial Dálias', 7.70),
  ('Jardim São Marcos (fase 1)', 7.70),
  ('Jardim Parada do Alto', 7.70),
  ('Vila Excelsior', 7.70),
  ('Vila Garrido', 7.70),
  ('Village D''Avignon', 7.70),
  ('Jardim São Marcos (fase 2)', 7.70),
  ('Jardim Beatriz (proposto)', 7.70),
  ('Jardim Norcross', 7.70),
  ('Jardim Villagio Torino', 7.70),
  ('Jardim Pagliato', 7.70),
  ('Chácaras Castanheira', 7.70),
  ('Jardim Casagrande', 7.70),
  ('Jardim Novo Bandeirantes', 7.70),
  ('Jardim Astro', 7.70),
  ('Jardim Monte Yehi', 7.70),
  ('Vila Espírito Santo', 7.70),
  ('Parque São Bento II', 7.70),
  ('Jardim Via Reggio', 7.70),
  ('Jardim Santa Marta', 7.70),
  ('Portal do Éden II', 7.70),
  ('Vila Berti', 7.70),
  ('Jardim Vittorio Emanuelle', 7.70),
  ('Jardim Pires de Mello', 7.70),
  ('Jardim Castanheira', 7.70),
  ('Parque Campolim', 7.70),
  ('Jardim Portobello', 7.70),
  ('Central Parque', 7.70),
  ('Vila Maria', 7.70),
  ('Jardim Gulaberto Moreira', 7.70),
  ('Vila Sônia', 7.70),
  ('Jardim Villagio Wanel', 7.70),
  ('Jardim Guarujá', 7.70),
  ('Parque Chácara Ondina', 7.70),
  ('Morros', 7.70),
  ('Portal do Éden I', 7.70),
  ('Vila João Romão', 7.70),
  ('Vila Sabiá', 7.70),
  ('Jardim Arco Íris', 7.70),
  ('Jardim Guadalajara', 7.70),
  ('Vila Paris', 7.70),
  ('Jardim Carolina', 7.70),
  ('Jardim Millenium', 7.70),
  ('Vila Novo Éden', 7.70),
  ('Conjunto Habitacional Júlio de Mesquita Filho', 7.70),
  ('Jardim Belvedere', 7.70),
  ('Jardim Montreal', 7.70),
  ('Jardim Boa Esperança', 7.70),
  ('Jardim Zezo Miguel', 7.70),
  ('Chácara São João', 7.70),
  ('Parque Bosque de São Bento II', 7.70),
  ('Terras do Sol Poente', 7.70)
ON CONFLICT (neighborhood) DO UPDATE SET fee = EXCLUDED.fee;
